# -*- coding: utf-8 -*-
"""030239230122.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dn7TubfrMAS4Xcw_8CjcGQxjUXgZMQNt
"""

import pandas as pd
import os

# Define the paths to the CSV files
files = {
    "domain_worker_desires.csv": "/content/domain_worker_desires.csv",
    "domain_worker_metadata.csv": "/content/domain_worker_metadata.csv",
    "task_statement_with_metadata.csv": "/content/task_statement_with_metadata.csv",
    "expert_rated_technological_capability.csv": "/content/expert_rated_technological_capability.csv"
}

# Load each CSV into a DataFrame and display the first 5 rows
df_desires = pd.read_csv(files["domain_worker_desires.csv"])
df_metadata = pd.read_csv(files["domain_worker_metadata.csv"])
df_task_statements = pd.read_csv(files["task_statement_with_metadata.csv"])
df_capabilities = pd.read_csv(files["expert_rated_technological_capability.csv"])

print("First 5 rows of domain_worker_desires.csv:")
display(df_desires.head())

print("\nFirst 5 rows of domain_worker_metadata.csv:")
display(df_metadata.head())

print("\nFirst 5 rows of task_statement_with_metadata.csv:")
display(df_task_statements.head())

print("\nFirst 5 rows of expert_rated_technological_capability.csv:")
display(df_capabilities.head())

"""After executing the cell above, you will have the data loaded into pandas DataFrames. Now, I will create the `app.py` file for the Streamlit application."""

with open('app.py', 'w', encoding='utf-8') as f:
    f.write('''
import streamlit as st
import pandas as pd
import plotly.express as px
import os

st.set_page_config(layout="wide")
st.title("📊 HỆ THỐNG PHÂN TÍCH & KHUYẾN NGHỊ AI AGENT TRONG KHMT")
st.caption("Ứng dụng phân tích dữ liệu tác vụ và năng lực tự động hóa thực tế")

# 1. ĐỌC DỮ LIỆU TUYỆT ĐỐI TỪ GOOGLE COLAB
@st.cache_data
def load_data():
    df_desires = pd.read_csv('/content/domain_worker_desires.csv') if os.path.exists('/content/domain_worker_desires.csv') else None
    df_metadata = pd.read_csv('/content/domain_worker_metadata.csv') if os.path.exists('/content/domain_worker_metadata.csv') else None
    df_tasks = pd.read_csv('/content/task_statement_with_metadata.csv') if os.path.exists('/content/task_statement_with_metadata.csv') else None
    df_experts = pd.read_csv('/content/expert_rated_technological_capability.csv') if os.path.exists('/content/expert_rated_technological_capability.csv') else None
    return df_desires, df_metadata, df_tasks, df_experts

df_desires, df_metadata, df_tasks, df_experts = load_data()

# TỰ ĐỘNG ĐỒNG BỘ CỘT NGHỀ NGHIỆP TRÁNH KEYERROR
standardized_col_name = 'Occupation_Standardized'
for df_item in [df_desires, df_metadata, df_tasks, df_experts]:
    if df_item is not None:
        # Clean column names by stripping whitespace
        df_item.columns = [str(col).strip() for col in df_item.columns]

        # Identify all columns that are 'occupation-like' (contains 'Occupation' or 'OCCUPATION')
        current_occupation_like_cols = [
            col for col in df_item.columns
            if standardized_col_name == col or any(keyword in col for keyword in ['Occupation', 'OCCUPATION', 'occupation'])
        ]

        primary_col_to_keep = None
        # Prioritize an already existing standardized column
        if standardized_col_name in current_occupation_like_cols:
            primary_col_to_keep = standardized_col_name
        elif current_occupation_like_cols: # If no standardized name, but other occupation cols exist
            primary_col_to_keep = current_occupation_like_cols[0]

        if primary_col_to_keep: # If an occupation column was found
            # Rename the primary column to standardized_col_name if it's not already
            if primary_col_to_keep != standardized_col_name:
                df_item.rename(columns={primary_col_to_keep: standardized_col_name}, inplace=True)
                # Update primary_col_to_keep for consistency after renaming
                primary_col_to_keep = standardized_col_name

            # Drop all other occupation-like columns, making sure to exclude the one we're keeping
            cols_to_drop = [
                col for col in current_occupation_like_cols
                if col != primary_col_to_keep
            ]
            if cols_to_drop:
                df_item.drop(columns=cols_to_drop, inplace=True)

# 2. XỬ LÝ BỘ LỌC NGÀNH NGHỀ KHOA HỌC MÁY TÍNH / CNTT
selected_job = "Software Developers"
if df_tasks is not None and 'Occupation_Standardized' in df_tasks.columns:
    all_jobs = list(set(df_tasks['Occupation_Standardized'].squeeze().dropna().tolist()))
    it_jobs = [job for job in all_jobs if any(kw in str(job) for kw in ['Computer', 'Software', 'Web', 'Developer', 'Data', 'Network', 'Programmer'])]
    if len(it_jobs) == 0:
        it_jobs = list(all_jobs[:10])

    st.sidebar.header("⚙️ Cấu hình bộ lọc")
    selected_job = st.sidebar.selectbox("Chọn ngành nghề cần phân tích:", it_jobs)

st.subheader(f"🎯 Kết quả phân tích tác vụ công việc ngành: {selected_job}")

# 3. TRỰC QUAN HÓA BIỂU ĐỒ BẰNG PLOTLY
col1, col2 = st.columns(2)

with col1:
    st.markdown("##### 🙋‍♂️ Mong muốn tự động hóa của Nhân sự (Worker Desires)")
    if df_desires is not None and 'Occupation_Standardized' in df_desires.columns:
        df_job_desire = df_desires[df_desires['Occupation_Standardized'] == selected_job]
        if not df_job_desire.empty and 'Automation Desire Rating' in df_job_desire.columns:
            fig1 = px.histogram(df_job_desire, x='Automation Desire Rating',
                                title="Mức độ mong muốn phân bổ theo số lượng tác vụ",
                                color_discrete_sequence=['#ff4b4b'])
            st.plotly_chart(fig1, use_container_width=True)
        else:
            st.info("Ngành này chưa có dữ liệu điểm khảo sát từ nhân viên.")
    else:
        st.error("Lỗi: Thiếu file domain_worker_desires.csv")

with col2:
    st.markdown("##### 🧠 Khả năng tự động hóa thực tế (Expert Capacity Rating)")
    if df_experts is not None and 'Occupation_Standardized' in df_experts.columns:
        df_job_expert = df_experts[df_experts['Occupation_Standardized'] == selected_job]
        if not df_job_expert.empty and 'Automation Capacity Rating' in df_job_expert.columns:
            fig2 = px.box(df_job_expert, y='Automation Capacity Rating',
                          title="Đánh giá từ chuyên gia về năng lực thực thi của AI",
                          color_discrete_sequence=['#1f77b4'])
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.info("Ngành này chưa có dữ liệu điểm đánh giá từ chuyên gia.")
    else:
        st.error("Lỗi: Thiếu file expert_rated_technological_capability.csv")

# 4. BÁO CÁO PHÂN TÍCH & KHUYẾN NGHỊ ỨNG DỤNG AI AGENT TRONG KHMT
st.markdown("---")
st.subheader("💡 Khuyến nghị Chiến lược triển khai AI Agent")

st.markdown(f"""
Dựa trên việc đối chiếu chéo dữ liệu thực tế cho vị trí **{selected_job}**, hệ thống đưa ra mô hình khuyến nghị như sau:

#### 📈 1. Phân tích khoảng cách (Gap Analysis)
* **Điểm chạm tối ưu:** Các tác vụ có điểm mong muốn tự động hóa từ nhân viên cao (*Desire Rating*) và khả năng công nghệ được chuyên gia đánh giá khả thi (*Capacity Rating > 4.0*) chính là vị trí lý tưởng để ứng dụng **AI Agent**. Nhóm việc này thường bao gồm: Viết tài liệu kiểm thử, rà soát log bảo mật, hoặc xử lý định dạng metadata thô.
* **Tối ưu kinh tế:** Dựa trên bảng lương ngành Khoa học máy tính (*Mean Annual Wage*), chi phí nhân công rất cao. Việc giải phóng kỹ sư khỏi tác vụ lặp đi lặp lại sẽ nâng cao hiệu suất làm việc tổng thể.

#### 🚀 2. Đề xuất Kiến trúc AI Agent phù hợp
* **Mô hình Single-Agent + RAG (Đại lý đơn nhiệm):**
    * *Ứng dụng:* Tự động hóa việc tra cứu tài liệu kỹ thuật, quản lý phân loại cấu trúc thông tin (dựa vào file `domain_worker_metadata.csv`).
    * *Đặc điểm:* Sử dụng một Agent kết hợp với bộ nhớ ngoài (Vector Database) để xử lý thông tin chính xác, nhanh chóng.
* **Hệ thống Multi-Agent (Hệ thống đa đại lý):**
    * *Ứng dụng:* Tự động hóa các chuỗi tác vụ phức tạp trong chu trình DevOps, CI/CD hoặc phát triển phần mềm dựa trên các mô tả yêu cầu kỹ thuật (*Task Statement*).
    * *Đặc điểm:* Triển khai một nhóm gồm nhiều Agent chuyên trách (Agent viết code, Agent rà soát lỗi bảo mật, Agent kiểm thử tự động) tương tác với nhau, có sự giám sát và phê duyệt chất lượng (*Quality Oversight*) từ kỹ sư con người nhằm đạt hiệu quả tối đa.
""")

# 5. PHỤ LỤC XEM TRƯỚC DỮ LIỆU GỐC
st.markdown("---")
st.subheader("📋 Phụ lục: Danh sách tác vụ thô từ hệ thống")
if df_tasks is not None:
    st.dataframe(df_tasks[df_tasks['Occupation_Standardized'] == selected_job].head(10), use_container_width=True)
''')
print("✅ File app.py đã được cấu hình và sẵn sàng!")

"""After creating the `app.py` file, we need to install `streamlit` and `localtunnel` to run the application."""

!pip install streamlit plotly

"""Next, we will install `localtunnel` to expose the Streamlit app to the internet."""

!npm install localtunnel

"""Now, let's run the Streamlit app and expose it using `localtunnel`. The output will include a public URL that you can use to access the application."""

!streamlit run app.py & npx localtunnel --port 8501

"""Once the last cell runs, it will output a public URL (e.g., `https://[random-string].loca.lt`). Click on that link to access your Streamlit application in a new browser tab. Please let me know if it works or if you encounter any errors!"""